name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    - name: Install dependencies
      run: dotnet restore ./OpenAdm.Cep.Api
    - name: Build
      run: dotnet build ./OpenAdm.Cep.Api --configuration Release
    - name: Install Chrome
      run: |
        apt-get update && apt-get install -y \
        wget \
        gnupg \
        unzip \
        libglib2.0-0 \
        libnss3 \
        libgconf-2-4 \
        libfontconfig1 \
        libxcb1 \
        libxcomposite1 \
        libxdamage1 \
        libxrandr2 \
        libxtst6 \
        libasound2 \
        libatk1.0-0 \
        libatk-bridge2.0-0 \
        libgtk-3-0

    - name: Install ChromeDriver
      run: |
        wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add - && \
        echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list && \
        apt-get update && \
        apt-get install -y google-chrome-stable
    - name: Test
      run: dotnet test ./OpenAdm.Cep.Test
    - name: Build-Image-Docker
      run: docker build -f OpenAdm.Cep.Api/Dockerfile --no-cache -t brunobentocaina/open-adm-cep:latest
    - name: Push
      run: |
        docker login -u brunobentocaina -p ${{ secrets.DOCKER_HUB_KEY }}
        docker push brunobentocaina/open-adm-cep:latest
