name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    - name: Install dependencies
      run: dotnet restore ./OpenAdm.Cep.Api
    - name: Build
      run: dotnet build ./OpenAdm.Cep.Api --configuration Release
    
    - name: Install Chrome dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libappindicator1 fonts-liberation
        sudo apt-get install -y wget gnupg2
        wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
        google-chrome --version

    - name: Install ChromeDriver
      run: |
        CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+')
        CHROME_DRIVER_VERSION=$(curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION)
        wget -N https://chromedriver.storage.googleapis.com/$CHROME_DRIVER_VERSION/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
        sudo mv -f chromedriver /usr/local/bin/chromedriver
        sudo chown root:root /usr/local/bin/chromedriver
        sudo chmod 0755 /usr/local/bin/chromedriver
        chromedriver --version

    - name: Add ChromeDriver to PATH
      run: echo "/usr/local/bin" >> $GITHUB_PATH

    - name: Test
      run: dotnet test ./OpenAdm.Cep.Test
    - name: Build-Image-Docker
      run: docker build -f OpenAdm.Cep.Api/Dockerfile --no-cache -t brunobentocaina/open-adm-cep:latest
    - name: Push
      run: |
        docker login -u brunobentocaina -p ${{ secrets.DOCKER_HUB_KEY }}
        docker push brunobentocaina/open-adm-cep:latest
